# Generated by Django 4.1.7 on 2023-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的UID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的UID')),
                ('flag', models.CharField(choices=[('superlike', '上海'), ('like', '右滑'), ('dislike', '左滑')], max_length=10)),
                ('dtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
