# Generated by Django 4.1.7 on 2023-03-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_play',
            field=models.BooleanField(default=True, verbose_name='是否自动播放视频'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8, verbose_name='匹配的性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(default=45, verbose_name='最大交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(default=18, verbose_name='最小交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vibration',
            field=models.BooleanField(default=True, verbose_name='是否开启震动'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=8),
        ),
    ]
